DEFINE TABLE newCalendr = ADDCOLUMNS(
            CALENDAR(DATE(2017,2,15),DATE(2018,5,15)), 
            "Year", YEAR([Date]),
            "MonthNumber", MONTH([Date]),
            "DayNumber", DAY([Date]),
            "Month", FORMAT([Date],"mmmm")
            )

//Produces the first date in the date table
EVALUATE
(
	STARTOFYEAR(newCalendr[Date])
)


//Produces the last date in the date table
EVALUATE
(
	ENDOFYEAR(newCalendr[Date])
)

EVALUATE
(
	ENDOFYEAR(newCalendr[Date],"2001-02-05")
)


//EVALUATE
//(
//	SELECTCOLUMNS(newCalendr,
//		"Date",[Date],
//		"--", " ")
//)
//


//Comment out and comment in the alernate lines (with and without default year)

EVALUATE
(
	SUMMARIZE
	(
		newCalendr,
		newCalendr[Year], 
		newCalendr[MonthNumber], 
		"Count of days in current month", COUNT(newCalendr[Date]),
		"---", "  ",
		"First date in current period", FORMAT(FIRSTDATE(newCalendr[Date]), "Medium Date"),
		"Last  date in current period", FORMAT(LASTDATE(newCalendr[Date]), "Medium Date"),
		"--", "  ",
		//"StartOfYear", FORMAT( STARTOFYEAR(newCalendr[Date]), "Medium Date"),
		"StartOfYear", FORMAT( STARTOFYEAR(newCalendr[Date],"0000-3-15"), "Medium Date"),
		"EndOfYear", 	FORMAT(ENDOFYEAR(newCalendr[Date],"0000-3-15" ), "Medium Date")
		//"EndOfYear", 	FORMAT(ENDOFYEAR(newCalendr[Date]), "Medium Date")
	)
)


