/*
//HOW TO DEFINE A TABLE

DEFINE 
TABLE blah = TOPN( 4, bi_manufacturer)

EVALUATE(
blah
)


//HOW TO DEFINE A CALCULATED TABLE

DEFINE 
COLUMN bi_salesFact[MyCol] = year(bi_salesFact[Date])
EVALUATE
(
DISTINCT( bi_salesFact[MyCol] )
)



*/



//EVALUATE 
//(
//DISTINCT( bi_product[Segment])
//)
//


//EVALUATE
//(
//)
//


//DEFINE MEASURE bi_sales[MyMeasure]=COUNTROWS(bi_salesFact)








/*
//static table, does not work with COUNTROWS
EVALUATE
(
	DATATABLE
	(
		"Table", STRING,
		"RowCount", INTEGER,
		{
			{"bi_product",100},
			{"bi_sentiment",200}
		}
	)
)

*/


//top N rows

//order by


