DEFINE 

TABLE segment_names=DISTINCT(bi_product[Segment])

EVALUATE
(
	CALCULATE(EARLIEST(segment_names))
)


VAR x=segment_names

TABLE manuf_segments_revenue=CALCULATETABLE
(
	SELECTCOLUMNS
	(
		bi_manufacturer,
		"MaufacturerId", bi_manufacturer[ManufacturerID],
		"MaufacturerName", bi_manufacturer[Manufacturer]
		CALCULATE(segment_names[0]),0
	)
)

EVALUATE
(
	manuf_segments_revenue
)

EVALUATE
(
	segment_names
)


/*
BloodPivot1Old = SUMMARIZECOLUMNS(
    vwBloodResultsObservationsMostRecent[ParticipantId],
    "Ast", 
    CALCULATE(MAX(vwBloodResultsObservationsMostRecent[ObservationValue]),FILTER(vwBloodResultsObservationsMostRecent, vwBloodResultsObservationsMostRecent[ObservationKey]="AST")),
    "Alt", 
    CALCULATE(MAX(vwBloodResultsObservationsMostRecent[ObservationValue]),FILTER(vwBloodResultsObservationsMostRecent, vwBloodResultsObservationsMostRecent[ObservationKey]="ALT")),
    "FERR", 
    CALCULATE(MAX(vwBloodResultsObservationsMostRecent[ObservationValue]),FILTER(vwBloodResultsObservationsMostRecent, vwBloodResultsObservationsMostRecent[ObservationKey]="FERR")),
    "GGT", 
    CALCULATE(MAX(vwBloodResultsObservationsMostRecent[ObservationValue]),FILTER(vwBloodResultsObservationsMostRecent, vwBloodResultsObservationsMostRecent[ObservationKey]="GGT"))


    )

*/

/*
what was I thinking?
How to get the index of the rows
*/

